name: pizzeria

services:
  nginx:
    depends_on: [ 'backend' ]
    build:
      context: ../
      dockerfile: devops/nginx/Dockerfile
    volumes:
      - './local-config-files/nginx.conf:/etc/nginx/nginx.conf'
      - '../:/var/www'
    ports:
      - "80:80"
    networks:
      - frontend
      - backend

  backend:
    build:
      context: ../
      dockerfile: devops/php-fpm/Dockerfile
    expose:
        - 9000
    volumes:
        - '../:/var/www'
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
