name: "Continuous Integration"

on:
  - pull_request

jobs:
  set-inputs:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - name: 'Set computed tag'
        id: set-tag
        run: echo "TAG=pizzeria/php-fpm:PR-${{ github.event.number }}" >> $GITHUB_OUTPUT

  build:
    needs: set-inputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build Docker Image from Source Code'
        uses: docker/build-push-action@v6
        with:
          file: devops/php-fpm/Dockerfile
          context: .
          tags: ${{ needs.set-inputs.outputs.tag }}
          outputs: type=docker,dest=/tmp/php-fpm.tar

      - name: 'Upload docker image'
        uses: actions/upload-artifact@v4
        with:
          name: php-fpm
          path: /tmp/php-fpm.tar
          retention-days: 1

  ci:
    needs: [set-inputs, build]
    strategy:
      fail-fast: false
      matrix:
        command: ["/var/www/vendor/bin/php-cs-fixer fix --dry-run --config=.php-cs-fixer.php", "/var/www/vendor/bin/phpstan analyse", "/var/www/vendor/bin/phpunit"]
    uses: ./.github/workflows/run-command.yml
    with:
      tag: ${{ needs.set-inputs.outputs.tag }}
      command: ${{ matrix.command }}
